apiVersion: batch/v1
kind: Job
metadata:
  name: rnn-imdb-trainer
  labels:
    app: rnn-imdb-trainer
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400

  template:
    metadata:
      labels:
        app: rnn-imdb-training
    spec:
      restartPolicy: Never
      containers:
        - name: rnn-trainer
          image: docker.io/jongonns/rnn-imdb-test:micro
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: HF_HOME
              value: /app/output/hf-cache

            - name: TRANSFORMERS_CACHE
              value: "/app/output/hf_cache"
            - name: HF_DATASETS_CACHE
              value: "/app/output/hf_cache/datasets"
          resources:
            requests:
              memory: "512Mi"   
              cpu: "250m"       
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - name: rnn-imdb-storage
              mountPath: /app/output/models
              subpath: rnn-imdb/models
            - name: rnn-imdb-storage
              mountPath: /app/output/logs
              subpath: rnn-imdb/logs
            - name: rnn-imdb-storage
              mountPath: /app/output/hf-cache
              subPath: rnn-imdb/hf-cache

      volumes:
        - name: rnn-imdb-storage
          persistentVolumeClaim:
            claimName: j-test