# -*- coding: utf-8 -*-
"""lezione_colab_intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WsTyoXBzWUue90vQzgNyrDVef9RAy4DS
"""
from google.colab import userdata
from transformers import AutoTokenizer
import os
try:
  my_secret = userdata.get('GROQ_API_KEY')
  print(f'valore chiave: {my_secret}')
except Exception as e:
  print(f'errore caricamento: {e}')

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
testo     = "questo è un testo di test per vedere come funziona la tokenizzazione"
tokens    = tokenizer.tokenize(testo)
input_ids = tokenizer.encode(testo)

print('"Testo originale: ', testo)
print('Tokens (subwords): ', tokens)
print('input IDs: ', input_ids)

