# -*- coding: utf-8 -*-
"""Tranformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1twAUXHFAyw3VLFWN9vEHqIoLIq18DQ8-
"""
from transformers import pipeline
import torch

print("Caricamento pipeline e model GPT-2")
'''si traspone molto facilmente ad altri modelli in base alla
task che voglio fare'''

try:
  generator = pipeline('text-generation', model = 'openai-community/gpt2')
  print('Caricamento avvenuto con successo')
except Exception as e:
  print(f'Errore nel caricamento della pipeline: {e}')
  generator = None

if generator:
  prompt = 'this is a test prompt'

  try:
    risultati = generator(
      prompt, 
      max_length = 100, 
      num_return_sequences = 1
    )

    print('\n--- Risultato generato---')
    print('Raw output', risultati)

    if risultati: #qui si spacchetta output raw
      testo_completo = risultati[0]['generated_text']
      print('\nTesto generato completo:')
      print(testo_completo)
    else:
      print('OH NOOO - ERRORE')
  except Exception as e:
    print(f'An error occurred during generation: {e}')

# ESEMPIO: sentiment-analysis
sentiment = pipeline('sentiment-analysis') #default model, ma posso specificarlo
print(sentiment('I love you, but not so much'))
print(sentiment('I hate myself'))

# ESEMPIO: traduzione
traduttore = pipeline("translation", model="Helsinki-NLP/opus-mt-en-it")
print(traduttore('I love you, but not so much'))

# ESEMPIO: generazione testo italiano
model_it     = 'GroNLP/gpt2-small-italian'
generator_it = pipeline('text-generation', model=model_it)
prompt       = "Odio il mondo intorno l'intelligenza artificiale"
print(generator_it(prompt, max_length=35, num_return_sequences=1)[0]['generated_text'])

