# -*- coding: utf-8 -*-
"""under_pipeline_transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojW5tT1ePSI_DSyhD1SfkVwO20xxmhR4
"""

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = 'openai-community/gpt2'
tokenizer  = AutoTokenizer.from_pretrained(model_name)
model      = AutoModelForCausalLM.from_pretrained(model_name)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model.to(device)
print(f'Modello caricato e spostato su {device}')

prompt = 'This is an example prompt for testing'
inputs = tokenizer(prompt, return_tensors='pt')
print('input ids: ',      inputs['input_ids'])
print('attention mask: ', inputs['attention_mask'])

inputs = {k: v.to(device) for k, v in inputs.items()}

print(f'Input spostati su {device}')

output_sequences = model.generate(
    input_ids            = inputs['input_ids'],
    attention_mask       = inputs['attention_mask'],
    max_length           = 50,
    do_sample            = True,
    num_return_sequences = 1,
    no_repeat_ngram_size = 2, #evita di ripetere coppie di parole
    pad_token_id         = tokenizer.eos_token_id #gestire correttamente lunghezza con i pad del tokenizer
)

print("output del metodo generate (token ids): ", output_sequences)
print('shape output: ', output_sequences.shape)
#genera i token fino alla fine della max length
#generazione: id del prompt originale + tutta la generazione

#va fatta decodifica dell'output tokenizzato
generated_text = tokenizer.decode(output_sequences[0], skip_special_tokens=True)
print('--- Testo generato ---')
print(generated_text)
